spring.config.import=optional:file:.env[.properties]
spring.application.name=inventoryservice
server.port=8080
#logging.level.root=DEBUG
firebase.database.url=${FIREBASE_DATABASE_URL}
firebase.service.account.path=${FIREBASE_SERVICE_ACCOUNT_PATH}
